-- Simple Quest Kit - QuestConfig

return {
    Quests = {
        {
            Id = "welcome_collect_coins",
            Title = "First Steps",
            Description = "Collect 5 coins around the village.",
            Type = "Collect",
            Target = "Coin",
            RequiredAmount = 5,
            Rewards = { Coins = 100 },
            Category = "NPC",
            NpcId = "GuideNPC",
            Repeatable = false,
        },
        {
            Id = "visit_forest",
            Title = "Explore the Forest",
            Description = "Walk into the forest area.",
            Type = "VisitArea",
            Target = "ForestZone",
            RequiredAmount = 1,
            Rewards = { Coins = 50 },
            Category = "Main",
            Repeatable = false,
        },
        {
            Id = "talk_to_guide",
            Title = "Meet the Guide",
            Description = "Talk to the village guide.",
            Type = "Interact",
            Target = "GuideNPC",
            RequiredAmount = 1,
            Rewards = { Coins = 25 },
            Category = "NPC",
            Repeatable = false,
        },
        {
            Id = "crystal_power",
            Title = "Crystal Power",
            Description = "Interact with the glowing crystal 3 times.",
            Type = "Interact",
            Target = "MagicCrystal",
            RequiredAmount = 3,
            Rewards = { Gems = 10 },
            Category = "Main",
            Repeatable = false,
        },
        {
            Id = "playtime_beginner",
            Title = "Stay A While",
            Description = "Play for 2 minutes.",
            Type = "Playtime",
            Target = "Time",
            RequiredAmount = 120,
            Rewards = { Coins = 150 },
            Category = "Main",
            Repeatable = false,
        },
        {
            Id = "custom_open_chest",
            Title = "Treasure Hunter",
            Description = "Open the demo treasure chest once.",
            Type = "CustomEvent",
            Target = "OpenChest",
            RequiredAmount = 1,
            Rewards = { Keys = 1 },
            Category = "Main",
            Repeatable = false,
        },
        {
            Id = "daily_collect_10_coins",
            Title = "Daily Collector",
            Description = "Collect 10 coins today.",
            Type = "Daily",
            BaseType = "Collect",
            Target = "Coin",
            RequiredAmount = 10,
            Rewards = { Coins = 250 },
            Category = "Daily",
            Repeatable = true,
            ResetSeconds = 86400,
        },
    }
}
